# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeyriFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyriFirebase
  pod 'keyri-pod'
  pod 'FirebaseAuth'

  target 'KeyriFirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyriFirebaseUITests' do
    # Pods for testing
  end

end
